//! The shared signing engine behind `sorocharge-x402` and `sorocharge-mpp`.
//!
//! This crate builds, signs, and verifies a `SorobanAuthorizationEntry` for
//! exactly one operation — a SEP-41 `transfer(from, to, amount)` — across
//! every credential shape CAP-71 defines (legacy `Address`, `AddressV2`, and
//! delegated signers). It knows nothing about x402 or MPP's wire formats;
//! the two protocol crates translate their own JSON shapes to and from the
//! types here. It also does not talk to Stellar RPC itself: callers submit
//! and poll for settlement through whichever RPC client their protocol
//! adapter uses.
//!
//! Every function that produces XDR is diffed byte-for-byte against a
//! fixture generated by the pinned `@stellar/stellar-sdk` (see
//! `tests/golden_vectors/` at the repo root) — this is the proof that the
//! entries this crate builds are the same bytes the reference SDK would
//! produce for the same inputs, not merely "look right."

#![deny(unsafe_code)]

mod effects;
mod entry;
mod error;
mod sign;
mod verify;

pub use effects::verify_transfer_effects;
pub use entry::{build_charge_entry, Address, ChargeParams, CredentialKind, UnsignedEntry};
pub use error::SorochargeError;
pub use sign::{sign_entry, SignedEntry, Signer};
pub use verify::verify_entry;
